to-metrion/to-metrion.github.io

_css/dark_ap_calc.css, _scripts/move_data.js, honkalculate.html, index.html
Due to x-btn having its width reduced, the z-move button text included a line break.
The move data now includes all moves used by RS mons so now the calc is a little closer to being able to be used as a complete RS lookup. Items and kinda sorta abilities are the only other things for this. Spit Up and Electrify were the only moves missing.
=> revert z-move button size

_scripts/damage.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- Changed a few mechanics for accuracy, mostly relating to -ate abilities (like Pixilate).
- I broke the mass calc in "All sets mode" when I fixed it calcing against custom sets. Oops. That's fixed.
- Improved mass calc performance. Using all 996 of USUM's sets as the baseline, it used to take around 5000ms to calc all sets. It now takes 1750ms, an improvement of about 65% in this case.
=> Improve mass calc preformance

_scripts/damage.js, _scripts/move_data.js, _scripts/shared_calc.js
- The strange boosting of weak moves is now implemented
- Loaded Dice defaults multihits to 4, as discussed
- Since the calc has move priority flags now, Dazzling clones and Psychic Terrain account for them
=> Tera boosts same-type weak moves

_scripts/damage.js, _scripts/shared_calc.js
- Adaptability's interaction with Terastallization is now correct (2.25x, 2x, and 1.5x STAB with Adaptability depending on move type and tera type)
- Non-Terastallized Tera Blast now correctly receives -ate boosts and type changes.
- Minor edge case bugfix for terrain seeds raising stats.
- Meteor Beam now adds +1 to its user's SpA stats when calculating Meteor Beam. (should be useful for RS players with Gigalith-RS)
- The mass calc now correctly calculates sets' HP stats by using the sets' supplied IVs instead of 31. (I had noticed that RS 1vAll mass calcs were calculating too little percentage damage)
=> More bugfixes and correctness updates

_scripts/honkalculate_calc.js, _scripts/shared_calc.js
This makes the mass calc about 40% faster. This puts total speed improvement for the mass calc at around 80% compared to when its code was first merged in.
For an attacker with 4 attacks in 1vAll mode, a mass calc takes around 1250ms.
In Allv1 mode, a mass calc takes around 1350ms.
=> Further optimize mass calc

_scripts/pokedex.js, _scripts/setdex_gen8_sets.js
This mainly fixes small things like Mega Charizard Y in SwSh or Ash-Greninja in SV being selectable.
G-max formes for all Pokemon except the Galar starters were removed because they do not affect calculations.
=> Update pokedex for formes

README.md, _scripts/damage_modern.js, _scripts/pokedex.js, _scripts/shared_calc.js, honkalculate.html, index.html
- Removed heavy weather buttons from the gen 8 Field.
- Updated the modern damage calc:
- Implemented Grass Pelt (didn't remember this was an ability)
- Reordered the multipliers as accurately as possible with current knowledge, referencing several sources
- Moved some modifiers to their correct category (BP, atk, def, and final)
- Changed the ability selector to add the current species's abilities to the top. This is designed to add to the current ability behavior, instead of altering it. If the loaded set has a specified ability it will be selected, then if the species has a specified ability it will be selected, then if the species only has one ability it will be selected, otherwise it will default to "(other)".
=> Add prepending species abilities

_scripts/honkalculate_calc.js, _scripts/move_data.js, _scripts/setdex_gen3_sets.js, _scripts/setdex_gen4_sets.js, _scripts/setdex_gen5_sets.js, _scripts/setdex_gen6_sets.js, _scripts/setdex_gen7_sets.js, _scripts/setdex_gen80_sets.js, _scripts/setdex_gen8_sets.js, _scripts/shared_calc.js
- Replaced current Revenge with Revenge (Doubled) to communicate to users how that move is calc'd, and added a 60 BP Revenge.
- Using the mass calc with gen 3 at level 50 will ignore the late-indexed sets that don't appear.
- Changing gens did not reset the Battery buttons.
=> Small improvements

_scripts/damage_modern.js, _scripts/game_data/item_data.js, _scripts/game_data/setdex_gen4_sets.js, _scripts/honkalculate_calc.js, _scripts/ko_chance.js
- Prevent move typing from being permanently changed by the mass calc (something with Pixilate would then have incorrect calcs).
- Added Float Stone functionality
- Somehow Sticky Barb was missing? Really only added it for RS sets completeness.
- Fixed a minor bug that could sometimes cause moves to display NaN in the chance to KO after accuracy.
=> Fix things that change move type for mass calc

_scripts/game_data/move_data.js, _scripts/game_data/setdex_gen4_sets.js, _scripts/game_data/setdex_gen5_sets.js, _scripts/game_data/setdex_gen6_sets.js, _scripts/game_data/setdex_gen7_sets.js, _scripts/game_data/setdex_gen80_sets.js, _scripts/game_data/setdex_gen8_sets.js
Since Avalanche was split into a 60 BP and 120 BP move, AI sets have been changed to use Avalanche (Doubled).
=> Sets now use Avalanche (Doubled)

_config.yml, _scripts/ap_calc.js, _scripts/damage_modern.js, _scripts/game_data/move_data.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- Triple Axel now calculates a 20, 40, and 60 BP hit. The prior method of calcing three 40 BP hits (or two 30's) was nicely close but not quite accurate. % chance to KO is still displayed as 90% for an OHKO, however. Maybe another day that'll get solved.
- Completely refactored the horrible Recoil and Recovery code in order to fix bugs. Recoil and Recovery text has been added to the long description. Shell Bell, Big Root, and Liquid Ooze have been implemented.
- Misty Explosion and Stored Power now properly check for isGrounded for applying their additional power/effects.
- Sword/Beads of Ruin and Proto/Quark now interact correctly with (Psyshock, Psystrike, Secret Sword). The incorrect defense stat was accounted for previously.
- I noticed that the description has an underutilized option …
=> Triple Axel, Recoil/Recovery text, and more

_scripts/damage_gen3.js, _scripts/damage_modern.js, _scripts/export.js, _scripts/game_data/move_data.js, _scripts/game_data/pokedex.js, _scripts/game_data/type_data.js, _scripts/honkalculate_calc.js, _scripts/import_custom.js, _scripts/shared_calc.js
- Fixed a bug that prevented any custom sets that were alternate formes to be saved, unless explicitly allowed like Megas or Gmax starters. Most notably, Aegislash formes could not be saved.
As part of this fix, alternate formes have been refactored to prevent this kind of issue in the future.
- Type dropdowns are more appealling
- Depreciated the None type from the type chart. This was part of removing the redundant None type from the dropdowns.
- Terastallizing now makes the secondary type visibly "(none)", consistent with loading a monotype Pokemon.
- The Nature Power Z Move code was made to be a bit cleaner. It's still not great.
- Fixed Tera's interactions with alternate forme Pokemon. Previously:
- Turning Terastallization off would only revert a Pokemon's types to the base …
=> Fix alternate forme set saving and more

_scripts/damage_modern.js, _scripts/game_data/stat_data.js, _scripts/import_custom.js, _scripts/ko_chance.js, _scripts/shared_calc.js
- Items like the Griseous Orb or Soul Dew that boost two move types will now work correctly with Terastallized Pokemon.
- The gen 5 genie signature moves are perfectly accurate in rain.
- Intimidate is now blocked by White Herb, and Mirror Armor no longer reflects it.
- Small bug fixes and code improvements.
Previously undocumented changes:
- If level is not specified in the Showdown format import, it will default to the current autolevel level.
- Status moves that are fatal to Shedinja now deal 1 damage. This PR includes an update to that logic.
- Regular Darmanitan had Gorilla Tactics as an ability instead of Sheer Force.
- Screens were using the singles damage reduction value in doubles. Text has been added to the move description to indicate when screens use the doubles reduction …
=> Shedinja damage and small updates

_css/ap_calc.css, _css/dark_ap_calc.css, _scripts/ap_calc.js, _scripts/damage_gen3.js, _scripts/damage_gen4.js, _scripts/damage_modern.js, _scripts/game_data/move_data.js, _scripts/honkalculate_calc.js, _scripts/import_custom.js, _scripts/shared_calc.js, index.html
- Several fixes for Parental Bond accuracy
- Power-Up Punch now calcs correctly in the mass calc.
- Resist berries only count the first hit.
- Implemented Neutralizing Gas, which included reworking how abilities are handled across the calc.
- Implemented Burn Up and Double Shock.
- Implemented Grav Apple.
- General code clean up and bug fixes.
- Included in this is splitting the modern damage calc into functions so it's a bit cleaner.
=> Parental Bond fixes, Neutralizing Gas, and code rework

_scripts/ap_calc.js, _scripts/shared_calc.js
- The weather and terrain code got a rewrite, making terrain a lot "stickier" than it was before. Terrain will now interact with abilities the same way weather does, and it will no longer be removed whenever any ability changes.
- Misty and Electric terrain will no longer interact with status and no longer block status menu options. The old implementation did not work perfectly, and I would prefer that users are able to account for circumstances where a mon is unaffected by terrain, or status'd before it entered terrain.
=> Update terrain and weather

_scripts/ap_calc.js, _scripts/damage_modern.js, _scripts/game_data/ability_data.js, _scripts/game_data/move_data.js, _scripts/honkalculate_calc.js
- Paralysis is now implemented in the calc, which means that it now affects the final speed number shown to the player and can now factor into speed-based calculations.
- Rock Head and Quick Feet have been implemented.
Previously undocumented change:
- Analytic has been changed to always apply its boost to the Pokemon with it, so it now requires users to properly apply it. The only thing this affects are two BDSP sets, since that's the only time that  the calc will auto-load Analytic for Pokemon with that ability (aside from user sets).
=> Implement paralysis and abilities

_scripts/damage_modern.js, _scripts/game_data/ability_data.js, _scripts/game_data/move_data.js, _scripts/game_data/pokedex.js, _scripts/shared_calc.js
Implemented the new Pokemon, moves, and abilities from The Indigo Disk.
- implemented Archaludon, Hydrapple, Gouging Fire, Raging Bolt, Iron Boulder, Iron Crown, Terapagos-Terastal, Terapagos-Stellar, and Pecharunt.
- Teragapos changes between its formes depending on Terastallization.
- implemented Electro Shot, Tera Starstorm, Fickle Beam, Thunderclap, Mighty Cleave, Tachyon Cutter, Hard Press, Alluring Voice, Temper Flare, Supercell Slam, Psychic Noise, Upper Hand, and Malignant Chain.
- implemented Tera Shell.
- updated the Pokedex.
Implemented new Stellar Terastallization mechanics.
- when terastallized to the Stellar type, all moves gain STAB.
- Stellar-type Tera Blast has been updated to become super-effective against Terastallized defenders.
Fixed a bug where Pokemon that use the …
=> The Indigo Disk Update

_scripts/damage_modern.js, _scripts/game_data/item_data.js, _scripts/game_data/move_data.js, _scripts/game_data/pokedex.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- In the pokedex, move data, and item data, gen-specific formes, Z moves, max moves, and items have been separated.
For the pokedex, this doesn't affect users at all. For moves and items, these will no longer display in the pulldowns.
All of this should make these parts of the calc a bit more maintainable.
Moves that were "dexited" from SwSh were removed from SwSh's move object.
- Bug fixes:
- fixed a bug that caused all gen 3 mass calcs to be wildly incorrect.
- fixed a minor bug that occurred when changing gens while certain formes were selected.
=> Separate gen-specific objects

_scripts/damage_gen3.js, _scripts/damage_gen4.js, _scripts/damage_modern.js, _scripts/shared_calc.js
- Custom sets now prepend to the set selector dropdown. They no longer appear under each species. They could though.
- Deep Sea Scale and Tooth now work correctly in gens 3-5
Previously undocumented change:
- Custom move BP now properly updates for the power calculation.
=> Custom sets top selector dropdown

_scripts/damage_gen3.js, _scripts/damage_gen4.js, _scripts/damage_modern.js, _scripts/game_data/item_data.js, _scripts/game_data/move_data.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- The description will display a move's type if the user manually selected a different type.
- Due to this, Aura Wheel (Dark) was removed from moves.
- The following moves that change type now interact correctly as Z and Max moves.
- Weather Ball, Nature Power, Terrain Pulse, Multi-Attack, Techno Blast.
- The Allv1 mass calc will calculate the AI using Z-moves if possible.
- Terrain Pulse now properly checks the attacker's grounded state.
- Pixilate and Glaciate correctly change Max moves again.
- Corrected Protosynthesis' weather check.
=> Print user-modified move type

_scripts/ap_calc.js, _scripts/damage_modern.js, _scripts/game_data/item_data.js, _scripts/honkalculate_calc.js, _scripts/ko_chance.js, _scripts/shared_calc.js, honkalculate.html
- The mass calc counts how many OHKOs occur for each mass calc now, displaying both a percentage and raw numbers.
- Fling was updated to cover more cases. All facility sets that use Fling are accounted for now, as well as most conceivable uses.
- Refactoring of several areas
- the mass calc table now populates from an array of objects instead of an array of arrays.
- objects now encapsulate the damage maps to store some additional meta information.
=> OHKO Counter

_scripts/ap_calc.js, _scripts/damage_modern.js, _scripts/shared_calc.js
Following on from Intimidate, abilities that affect a stat now reflect this as a stat stage. Currently this affects Intrepid Sword, Dauntless Shield, and Embody Aspect.
This finishes the groundwork for applying the checkbox to more abilities than Intimidate.
Previously undocumented changes:
- Adrenaline Orb has been implemented, along with several Intimidate interactions.
- Mirror Armor's interactions with Intimidate has been reimplemented due to Intimidate's effect being clearly visible.
- Iron Ball Flying types now apply type interactions correctly.
- Stellar Terastallized defenders no longer print anything for a Tera type.
=> Stat Abilities apply as visible stages

_scripts/damage_gen3.js, _scripts/damage_gen4.js, _scripts/damage_modern.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- Electromorphosis, Wind Power, Marvel Scale, Guts, Quick Feet, Overgrow, Blaze, Torrent, and Swarm have been added as checkbox abilities.
Bug fixes:
- Pokemon with alternate formes will load their saved ability correctly.
- Activated Intimidate undoes its effect when the set changes.
- MassPokemon now only default an activatable ability to true if the checkbox will default to checked for a user's Pokemon in mass calc mode.
=> More checkbox abilities

_scripts/ap_calc.js, _scripts/damage_modern.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js, honkalculate.html, index.html
- Seed items activated in terrain now apply a visible stat stage.
- Activated Seed items and Adrenaline Orb no longer count as a held item for Acrobatics and Knock Off.
- Poltergeist is the only other move that could have been influenced by this change. It does not currently have logic in the calc so nothing will be added for it at this time.
- The Minimize button will be indefinitely hidden/unusable. The power modifier it applied is not correct to every move in every gen and it applied a non-visible evasion mod.
=> Seed update

_scripts/damage_gen3.js, _scripts/damage_gen4.js, _scripts/damage_modern.js, _scripts/game_data/item_data.js, _scripts/game_data/setdex_gen4_sets.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js
- Checkboxes have been added for Slow Start, Defeatist, and Unburden.
- Slow Start and Crush Grip have been implemented in gen 4.
- Unburden has functionality now, including detection of when it should activate even while unchecked (i.e. a seed has been consumed by terrain).
- Shell Side Arm has been fixed.
- SwSh has had the Plate items removed from its item pool. This also sets up things for future gens to easily remove plates.
=> Small upgrades

_scripts/honkalculate_calc.js, _scripts/shared_calc.js, honkalculate.html
- Speed is now a column in the mass calc output table, highlighting opponents that outspeed the user in red and ties in yellow.
- A user's Pokemon with a low speed IV will instead highlight for underspeeding opponents.
- Seismic Toss is now accurately calculating for best move in the mass calc. It will be better selected as the best move in some scenarios, but this selection is still likely not perfectly ideal.
- Captured a fix from EisenTree's calc where the calc can error when loading a set with Triple Axel.
=> Mass calc improvements

_scripts/damage_modern.js, _scripts/export.js
- Cleaned up the first hit code. The new approach to first hit recalculation is both easier to understand and removed complicated conditionals.
- This change isn't meant to affect anything the user sees since it was a code rework. However, this should have fixed some interactions between things that use the first hit system.
- Added Knock Off to the first hit system.
Previous undocumented changes:
- Instances of items that had their names changed in gen 6 (e.g. "BlackGlasses" -> "Black Glasses") were replaced with their new names across the calc. The old names are still used for set import and export, for purposes of interfacing with other applications that use Showdown format.
=> Refine first hit system

_scripts/damage_gen4.js, _scripts/honkalculate_calc.js, _scripts/shared_calc.js, honkalculate.html
- RS sets now appear as the first set instead of last for a species in the set dropdown.
- RS is now the default mass calc mode for SwSh.
- Tower wasn't completely forgotten, however. The AI will now default to a Dynamax level of 0 instead of 10.
- Gen 4 will now print first hit only text for resist berries.
- Some code improvement by refactoring.
=> RS favoritism

_scripts/import_custom.js
Proposing to use the showdown nickname, as the spreadName, this makes importing groups of the same mon easier (i.e. 17 for hall).
I am concerned about usability where there is a nickname the user does not want, checking if the entry box is not the default text could be an option but is not flawless.
=> Use nickname as spreadName
