to-metrion/to-metrion.github.io

_scripts/ap_calc.js
_scripts/move_data.js

Certain moves would have incorrect Max Move power, just due to the structure of the logic.

Add Peck and a bug fix for Max Moves

---

_scripts/ap_calc.js
_scripts/honkalculate_calc.js
_scripts/ko_chance.js
_scripts/setdex_gen5_sets.js
_scripts/shared_calc.js

Also make the dynamax button change all loves to max moves in mass calc.
Also update move names like SolarBeam in the gen 5 setdex so they are properly recognized.

simplify text in mass calc table

---

_scripts/ap_calc.js
_scripts/export.js
_scripts/setdex_custom.js
_scripts/shared_calc.js

- the set importer and exporter handles Megas much better now, and can actually accept sets from Showdown now. It currently doesn't export to Showdown format quite properly, this will be changed later.
- last selected move stays, as discussed

QOL updates

---

_scripts/ap_calc.js
_scripts/damage.js
_scripts/honkalculate_calc.js
_scripts/ko_chance.js
_scripts/move_data.js
_scripts/shared_calc.js
honkalculate.html
index.html

SV CODE UPDATE!
Moves:
Collision Course
Electro Drift
Last Respects
Population Bomb
Raging Bull
Triple Dive
Barb Barrage
Infernal Parade
Abilities:
Anger Shell
Earth Eater
Well-Baked Body
Hadron Engine
Orichalcum Pulse
Protosynthesis
Quark Drive
Sharpness
Rocky Payload
Wind Rider
Purifying Salt
Supreme Overlord
Ruin Abilities
Items:
Clear Amulet
Punching Glove
Snow mechanics have also been added.

SV code for items and abilities

---

_scripts/damage.js
_scripts/honkalculate_calc.js
_scripts/shared_calc.js

Protosynthesis/Quark Drive now apply a multiplier to the stat instead of adding a stat boost
Supreme Overlord gets an additional 10% added if there are any fainted allies (damage text was changed too)
Punching Glove does not stack with Iron Fist
Reverted Terrain boosts to 1.3 in BDSP and SV
Updated speed to properly update in terrain (like Surge Surfer)

fix SV mechanics

---

_scripts/ap_calc.js
_scripts/damage.js
_scripts/honkalculate_calc.js
_scripts/shared_calc.js
honkalculate.html
index.html

Custom sets are now no longer included in the mass calc results table.
A new button for Steely Spirit is added; the effect is no longer locked to an ability.
Some minor improvements to damage result text.

Remove custom sets from mass calc results

---

_css/dark_ap_calc.css
_scripts/damage_modern.js
_scripts/honkalculate_calc.js
_scripts/setdex_gen4_sets.js
_scripts/shared_calc.js
honkalculate.html
index.html

Added a new menu to the field for USUM and prior games for relevant AI IV tiers.
Also fixed the reported damage berry description bug.

Add AI auto IVs

---

_scripts/damage_modern.js
_scripts/game_data/item_data.js
_scripts/honkalculate_calc.js

- Permanent changes to move properties have been accounted for (these affect mass calcs).
- Added a couple of items that were missing from RS sets.
- Also added some edge case handling for some recent additions.

Minor corrections and refactoring

---

_scripts/damage_modern.js
_scripts/honkalculate_calc.js

- Hydro Steam's effect was changed from a BP mod to a weather mod.
- Implemented Utility Umbrella.
- After thinking about it for a few weeks, Pokemon with a Ruin ability cannot be affected by that same opposing Ruin.

Utility Umbrella and Ruins

---

_scripts/game_data/setdex_gen8_sets.js
_scripts/import_custom.js
_scripts/shared_calc.js
honkalculate.html
index.html

Added a checkbox so that when it is checked when a custom set is saved, when that set is later loaded, it starts either Dynamaxed or Terastallized.

Add start with gimmick checkbox

---

_scripts/ap_calc.js
_scripts/shared_calc.js

- Implemented Merciless to auto-select crits for One Guy.
- The battle tower symbol will now link to the corresponding Smogon leaderboard thread based on which gen is currently selected.

Implement Merciless

---

_scripts/damage_gen3.js
_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/honkalculate_calc.js
_scripts/shared_calc.js

- The mass calc has a minor optimization for speed, seeing about an 8% increase in speed compared to before this commit.
- (checked against an attacker using 4 attacks in 1vAll vs all USUM sets, about 1000 sets)
- Refactored some damage code to allow for the speedup.
- Fixed an issue with gen 4's damage code that could have caused incorrect mass calcs.

Minor mass calc optimization

---

_css/dark_ap_calc.css
_scripts/ap_calc.js
index.html

yoinked this from smogon lol (thanks DimK19)

Click-to-copy result text

---

_scripts/damage_modern.js
_scripts/game_data/item_data.js

- Griseous Core, Adamant Crystal, and Lustrous Globe have been added.
- Knock Off has been updated with missing item interactions. The Rusted items have been removed as part of this.
- Solar Blade never had its power halved in bad weather. Utility Umbrella no longer prevents bad weather from halving Solar Beam's power.

Add PLA/SV Creation Trio items

---

_scripts/ap_calc.js
_scripts/damage_gen4.js
_scripts/damage_modern.js

- Fixed Parental Bond causing an exception and breaking the calc.
- Fixed several inaccuracies of the recoil/recovery calculation code.

Hot-fix bugs

---

_scripts/damage_gen3.js
_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/shared_calc.js
honkalculate.html
index.html

- Charge has been added to the field effects. Frankly it's strange that Foresight/Odor Sleuth were implemented but Charge never was.
- ProtoQuark now affects the modified speed field if speed is its highest stat. It was always designed to affect modified speed but probably has never done that until now. This behavior worked correctly in the mass calc, where it was useless!
- Also did some extra work to ensure that ProtoQuark would properly find and boost the correct stat.

Add Charge as a field effect

---

_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/honkalculate_calc.js
_scripts/shared_calc.js
honkalculate.html
index.html

- The Mega AI sets did not calculate as Mega, meaning stats, typing, and abilities were never loading properly. This has always been broken since it's broken on turskain's calc.
- Minor adjustments.

Fix Mass Calc Megas

---

_scripts/damage_modern.js
_scripts/game_data/ability_data.js
_scripts/game_data/move_data.js
_scripts/game_data/pokedex.js
_scripts/shared_calc.js

Implemented the new Pokemon, moves, and abilities from The Teal Mask. Details to be added later.

The Teal Mask Update

---

_scripts/ap_calc.js
_scripts/damage_modern.js
_scripts/honkalculate_calc.js
_scripts/ko_chance.js
_scripts/shared_calc.js

Implemented damage maps.
- Damage maps are map structures that map a value of damage to the number of ways that damage number can occur. For the key:value pair, the key is a damage value (or accumulated damage value) and the value is the number of ways that damage value can occur.
- In short, these maps allow for relatively easy and quick calculations of the many ways a damage range can damage something.
- This was done to calculate multihit moves' chance to KO more accurately and their interactions with resist berries.
- The ko_chance code was rewritten from scratch, and ended up close to what was already there. This code was made simpler and  more readable and some bugs were fixed in this process.
- Resist berries now only apply to the first hit, or only the first strike of a multihit …

Implement damage maps

---

_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/game_data/move_data.js
_scripts/honkalculate_calc.js
_scripts/ko_chance.js
_scripts/shared_calc.js

- Tera Starstorm has been corrected to be Stellar type when Terastallized.
- Tera Stellar and Throat Spray now use the first hit system, displaying the different damage values to the user.
- The mass calc now treats Leon's Charizard as Dynamax, both offensively and defensively.

Additions to "first hit" system

---

_scripts/damage_gen3.js
_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/game_data/move_data.js

- Ground moves will apply type effectiveness for Iron Ball, Gravity, and whether the defender is Flying-type, Levitating, or any combination of those effects.
- Triage-affected moves are now treated as having priority.
- Pledge-boosted moves now apply STAB regardless.

Iron Ball interactions

---

_scripts/ap_calc.js
_scripts/damage_modern.js
_scripts/shared_calc.js

- The field Weakness Policy, +1 All, and +2 All buttons now apply visible stat stages
- General code improvements and refactoring.

Weakness Policy changes stat stages

---

_scripts/ap_calc.js
_scripts/damage_gen3.js
_scripts/damage_gen4.js
_scripts/damage_modern.js
_scripts/game_data/move_data.js
_scripts/import_custom.js
_scripts/ko_chance.js
_scripts/shared_calc.js

- Updates and bug fixes for KO chance.
- Multihit moves and Triple Axel have been improved.
- Knock Off negates certain end-of-turn item interactions.
- Tera Shell interactions and display has been improved.
- Gems have been added to the first hit system.

Improve multihit and Triple Axel interactions with ko chance.

---

_scripts/damage_modern.js
_scripts/ko_chance.js

- ko_chance had parts of its code relating to eot, berry recovery, and threshold checks refactored. Some fixes were made for toxic damage and orb damage.
- Sharpness has been corrected from an attack modifier to a base power modifier.

Rework/Refactor ko_chance
